export const PRIMARY_COLOR = '#4c0788'
export const SECONDARY_COLOR = '#8465ab'
export const WHITE_COLOR = '#ffffff'
export const BACK_BUTTON_TEXT_COLOR = '#4c0788'
export const BACK_BUTTON_BG_COLOR = '#ffffff' 