export const ADMIN_WELCOME_PATH = '/admin'
export const ADMIN_LOGIN_PATH = '/admin/login'
export const ADMIN_SIGNUP_PATH = '/admin/signup'
export const ADMIN_RECOVERPASSWORD_PATH = '/admin/recoverPassword'
export const ADMIN_RECOVERPASSWORDSUCCESS_PATH = '/admin/recoverPassword/success'
